plugins {
    id 'fabric-loom' version '1.18.2'
    id 'java'
}

// Minecraft 1.21 - 1.21.11 (compiled against 1.21.8, see gradle.properties)
def target = "mc1.21.x"
version = "${project.mod_version}+${target}"

base {
    archivesName = "voicechat-audio-distance-fabric"
}

repositories {
    mavenCentral()
    maven {
        name = "henkelmax.public"
        url = 'https://maven.maxhenkel.de/repository/public'
    }
    maven {
        name = "TerraformersMC"
        url = 'https://maven.terraformersmc.com/releases'
    }
}

sourceSets {
    main {
        java {
            srcDir "${rootDir}/shared/mc-all/src/main/java"
            srcDir "${rootDir}/shared/mc-1.20-1.21/src/main/java"
        }
    }
}

dependencies {
    implementation project(':common')

    minecraft "com.mojang:minecraft:${project.mc121_minecraft}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.mc121_fabric_loader}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.mc121_fabric_api}"

    compileOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    modCompileOnly "com.terraformersmc:modmenu:${project.mc121_modmenu}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

processResources {
    inputs.property "version", project.version

    filesMatching(["fabric.mod.json", "META-INF/*.toml"]) {
        expand "version": project.version
    }
}

jar {
    from project(':common').sourceSets.main.output
}

remapJar {
    archiveClassifier = ''
}
