modLoader = "lowcodefml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/Shamanalle/voicechat-audio-distance/issues"

[[mods]]
modId = "vc_audio_distance"
version = "${version}"
displayName = "Simple Voice Chat - Audio Distance Addon"
displayURL = "https://github.com/Shamanalle/voicechat-audio-distance"
logoFile = "assets/vc-audio-distance/icon.png"
authors = "Kasper"
description = '''
Realistic 3D audio physics, distance falloff curves, and physical obstacle sound occlusion addon for Simple Voice Chat.
'''

[[dependencies.vc_audio_distance]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.11]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc_audio_distance]]
modId = "voicechat"
type = "required"
versionRange = "[2.6.0,)"
ordering = "AFTER"
side = "CLIENT"
