plugins {
    id 'java-library'
}

base {
    archivesName = "voicechat-audio-distance-common"
}

repositories {
    mavenCentral()
    maven {
        name = "henkelmax.public"
        url = 'https://maven.maxhenkel.de/repository/public'
    }
}

dependencies {
    implementation "org.slf4j:slf4j-api:${project.slf4j_version}"

    // Provided at runtime by Simple Voice Chat and Minecraft
    compileOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    compileOnly "org.lwjgl:lwjgl:${project.lwjgl_version}"
    compileOnly "org.lwjgl:lwjgl-openal:${project.lwjgl_version}"

    testImplementation "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

test {
    useJUnitPlatform()
}
